### ISSUE TITLE
[FEAT] 이메일 문서 보완

### ISSUE THREAD

**Issue by cjh-19** [KW-MUJI/BE#235]
## 📝 Issue Description

인증번호 인증 및 팀플 시작 버튼 클릭 이벤트 때, 이메일 전송 시, 메일 문서 보완

## ✔️ To-do

- [x] 메일 html 보완

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Enhanced the email HTML content for both the authentication number and team project start notifications. The changes include better formatting, more informative content, and improved visual appeal while maintaining the existing code structure and styling.

You can review changes in this commit: https://github.com/mnmnk43434/KW-MUJI-BE-235/commit/2fad4783ebc6a96081e2bbb5c4b7456ecef9575e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
